// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	Api_keyScopes = "api_key.Scopes"
)

// Defines values for SearchKindleParamsRegion.
const (
	Au SearchKindleParamsRegion = "au"
	Ca SearchKindleParamsRegion = "ca"
	De SearchKindleParamsRegion = "de"
	Es SearchKindleParamsRegion = "es"
	Fr SearchKindleParamsRegion = "fr"
	In SearchKindleParamsRegion = "in"
	It SearchKindleParamsRegion = "it"
	Jp SearchKindleParamsRegion = "jp"
	Uk SearchKindleParamsRegion = "uk"
	Us SearchKindleParamsRegion = "us"
)

// BookMetadata defines model for BookMetadata.
type BookMetadata struct {
	Asin   *string `json:"asin,omitempty"`
	Author *string `json:"author,omitempty"`

	// Cover URL to the cover image
	Cover       *string `json:"cover,omitempty"`
	Description *string `json:"description,omitempty"`

	// Duration Duration in minutes
	Duration      *int              `json:"duration,omitempty"`
	Genres        *[]string         `json:"genres,omitempty"`
	Isbn          *string           `json:"isbn,omitempty"`
	Language      *string           `json:"language,omitempty"`
	Narrator      *string           `json:"narrator,omitempty"`
	PublishedYear *string           `json:"publishedYear,omitempty"`
	Publisher     *string           `json:"publisher,omitempty"`
	Series        *[]SeriesMetadata `json:"series,omitempty"`
	Subtitle      *string           `json:"subtitle,omitempty"`
	Tags          *[]string         `json:"tags,omitempty"`
	Title         string            `json:"title"`
}

// SeriesMetadata defines model for SeriesMetadata.
type SeriesMetadata struct {
	Sequence *string `json:"sequence,omitempty"`
	Series   string  `json:"series"`
}

// Author defines model for author.
type Author = string

// Query defines model for query.
type Query = string

// N200 defines model for 200.
type N200 struct {
	Matches *[]BookMetadata `json:"matches,omitempty"`
}

// N400 defines model for 400.
type N400 struct {
	Error *string `json:"error,omitempty"`
}

// N401 defines model for 401.
type N401 struct {
	Error *string `json:"error,omitempty"`
}

// N500 defines model for 500.
type N500 struct {
	Error *string `json:"error,omitempty"`
}

// SearchGoodreadsParams defines parameters for SearchGoodreads.
type SearchGoodreadsParams struct {
	Query  Query   `form:"query" json:"query"`
	Author *Author `form:"author,omitempty" json:"author,omitempty"`
}

// SearchKindleParams defines parameters for SearchKindle.
type SearchKindleParams struct {
	Query  Query   `form:"query" json:"query"`
	Author *Author `form:"author,omitempty" json:"author,omitempty"`
}

// SearchKindleParamsRegion defines parameters for SearchKindle.
type SearchKindleParamsRegion string

// SearchThaliaParams defines parameters for SearchThalia.
type SearchThaliaParams struct {
	Query  Query   `form:"query" json:"query"`
	Author *Author `form:"author,omitempty" json:"author,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Search for books using goodreads
	// (GET /goodreads/search)
	SearchGoodreads(w http.ResponseWriter, r *http.Request, params SearchGoodreadsParams)
	// Search for books using kindle
	// (GET /kindle/{region}/search)
	SearchKindle(w http.ResponseWriter, r *http.Request, region SearchKindleParamsRegion, params SearchKindleParams)
	// Search for books using thalia
	// (GET /thalia/search)
	SearchThalia(w http.ResponseWriter, r *http.Request, params SearchThaliaParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Search for books using goodreads
// (GET /goodreads/search)
func (_ Unimplemented) SearchGoodreads(w http.ResponseWriter, r *http.Request, params SearchGoodreadsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search for books using kindle
// (GET /kindle/{region}/search)
func (_ Unimplemented) SearchKindle(w http.ResponseWriter, r *http.Request, region SearchKindleParamsRegion, params SearchKindleParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Search for books using thalia
// (GET /thalia/search)
func (_ Unimplemented) SearchThalia(w http.ResponseWriter, r *http.Request, params SearchThaliaParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SearchGoodreads operation middleware
func (siw *ServerInterfaceWrapper) SearchGoodreads(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, Api_keyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchGoodreadsParams

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	// ------------- Optional query parameter "author" -------------

	err = runtime.BindQueryParameter("form", true, false, "author", r.URL.Query(), &params.Author)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchGoodreads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchKindle operation middleware
func (siw *ServerInterfaceWrapper) SearchKindle(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "region" -------------
	var region SearchKindleParamsRegion

	err = runtime.BindStyledParameterWithOptions("simple", "region", chi.URLParam(r, "region"), &region, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: false})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "region", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, Api_keyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchKindleParams

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	// ------------- Optional query parameter "author" -------------

	err = runtime.BindQueryParameter("form", true, false, "author", r.URL.Query(), &params.Author)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchKindle(w, r, region, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchThalia operation middleware
func (siw *ServerInterfaceWrapper) SearchThalia(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, Api_keyScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchThaliaParams

	// ------------- Required query parameter "query" -------------

	if paramValue := r.URL.Query().Get("query"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "query"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "query", r.URL.Query(), &params.Query)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "query", Err: err})
		return
	}

	// ------------- Optional query parameter "author" -------------

	err = runtime.BindQueryParameter("form", true, false, "author", r.URL.Query(), &params.Author)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "author", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchThalia(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/goodreads/search", wrapper.SearchGoodreads)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/kindle/{region}/search", wrapper.SearchKindle)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/thalia/search", wrapper.SearchThalia)
	})

	return r
}

type N200JSONResponse struct {
	Matches *[]BookMetadata `json:"matches,omitempty"`
}

type N400JSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type N401JSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type N500JSONResponse struct {
	Error *string `json:"error,omitempty"`
}

type SearchGoodreadsRequestObject struct {
	Params SearchGoodreadsParams
}

type SearchGoodreadsResponseObject interface {
	VisitSearchGoodreadsResponse(w http.ResponseWriter) error
}

type SearchGoodreads200JSONResponse struct{ N200JSONResponse }

func (response SearchGoodreads200JSONResponse) VisitSearchGoodreadsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchGoodreads400JSONResponse struct{ N400JSONResponse }

func (response SearchGoodreads400JSONResponse) VisitSearchGoodreadsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchGoodreads401JSONResponse struct{ N401JSONResponse }

func (response SearchGoodreads401JSONResponse) VisitSearchGoodreadsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SearchGoodreads500JSONResponse struct{ N500JSONResponse }

func (response SearchGoodreads500JSONResponse) VisitSearchGoodreadsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SearchKindleRequestObject struct {
	Region SearchKindleParamsRegion `json:"region,omitempty"`
	Params SearchKindleParams
}

type SearchKindleResponseObject interface {
	VisitSearchKindleResponse(w http.ResponseWriter) error
}

type SearchKindle200JSONResponse struct{ N200JSONResponse }

func (response SearchKindle200JSONResponse) VisitSearchKindleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchKindle400JSONResponse struct{ N400JSONResponse }

func (response SearchKindle400JSONResponse) VisitSearchKindleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchKindle401JSONResponse struct{ N401JSONResponse }

func (response SearchKindle401JSONResponse) VisitSearchKindleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SearchKindle500JSONResponse struct{ N500JSONResponse }

func (response SearchKindle500JSONResponse) VisitSearchKindleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SearchThaliaRequestObject struct {
	Params SearchThaliaParams
}

type SearchThaliaResponseObject interface {
	VisitSearchThaliaResponse(w http.ResponseWriter) error
}

type SearchThalia200JSONResponse struct{ N200JSONResponse }

func (response SearchThalia200JSONResponse) VisitSearchThaliaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SearchThalia400JSONResponse struct{ N400JSONResponse }

func (response SearchThalia400JSONResponse) VisitSearchThaliaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SearchThalia401JSONResponse struct{ N401JSONResponse }

func (response SearchThalia401JSONResponse) VisitSearchThaliaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SearchThalia500JSONResponse struct{ N500JSONResponse }

func (response SearchThalia500JSONResponse) VisitSearchThaliaResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Search for books using goodreads
	// (GET /goodreads/search)
	SearchGoodreads(ctx context.Context, request SearchGoodreadsRequestObject) (SearchGoodreadsResponseObject, error)
	// Search for books using kindle
	// (GET /kindle/{region}/search)
	SearchKindle(ctx context.Context, request SearchKindleRequestObject) (SearchKindleResponseObject, error)
	// Search for books using thalia
	// (GET /thalia/search)
	SearchThalia(ctx context.Context, request SearchThaliaRequestObject) (SearchThaliaResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// SearchGoodreads operation middleware
func (sh *strictHandler) SearchGoodreads(w http.ResponseWriter, r *http.Request, params SearchGoodreadsParams) {
	var request SearchGoodreadsRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchGoodreads(ctx, request.(SearchGoodreadsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchGoodreads")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchGoodreadsResponseObject); ok {
		if err := validResponse.VisitSearchGoodreadsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchKindle operation middleware
func (sh *strictHandler) SearchKindle(w http.ResponseWriter, r *http.Request, region SearchKindleParamsRegion, params SearchKindleParams) {
	var request SearchKindleRequestObject

	request.Region = region
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchKindle(ctx, request.(SearchKindleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchKindle")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchKindleResponseObject); ok {
		if err := validResponse.VisitSearchKindleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SearchThalia operation middleware
func (sh *strictHandler) SearchThalia(w http.ResponseWriter, r *http.Request, params SearchThaliaParams) {
	var request SearchThaliaRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SearchThalia(ctx, request.(SearchThaliaRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchThalia")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SearchThaliaResponseObject); ok {
		if err := validResponse.VisitSearchThaliaResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWTXPbNhD9Kxy0R44oN+mFt6TttBondcd2Dq1H04HINQmLBODFwjOqh/+9swBp6oOS",
	"4uSQSy4SiX27+7DYh+WzKExrjQZNTuTPwkqULRBgeJOeaoP8pLTIxaMH3IhUaNmCyAdrKlxRQysZRhvL",
	"FkeodCW6Lu19jkQYXhEevUIoRU7o4VTAjsHOGu0gMPxpPue/wmgCTYGztY0qJCmjswdnNK+N8SwaC0gq",
	"ereSijo+KoI2PPyIcC9y8UM2FiaL/i57b8z6I5AsJUnRpQM7iSg3Ybf9glk9QEGRbgmuQGWZj8jF1SX7",
	"vf0q1oAYD+Ww2mfzv5dlcg2PHhxFIhffiMgnHdtH/QclM/n5m5VkoQlQyya5AXwCTH4LsQ4dh7YMCXc6",
	"4YCOdCrQvTfYSuIO4YV0n126JbADU2GeIFj26nb9ISGTUA1JQCSqlRVMxd7xm0hQepSDcTfHr70lUTpp",
	"lfYETqTjZpSmMZ/SBBUgB6xA456YDpLuKiYVyq12KxUWJnbTSF153ulUVM3x6EghrV81ytVQ/g3yNGLa",
	"6gDVK+6ImwA/fkukwvkVKWqmt0KyemUJj8Xqtu/Vux62POjrVOwxPuhmx/eFLuBMdU6n73HLSV1B4VHR",
	"5oZL2CvIqn/XMA6OGmQJOE6Od59u/7i6Xvzz7nZx9efYL9KqS9hElSt9b9i/UQVoF9j3zh8XtyIVHhsO",
	"TGRdnmXGgnbGYwEzg1XWO7mMsWORxS/ekWmToVjJX2ieVGT2BOiifuazi9mcvTiotErk4s1sPpuLVFhJ",
	"ddhgVhlTIsjSZQ4kFjUvVkCHarwJ5uTeYLIyZu0S75Sukhd/EfJExS7KF4fft+zbU/1uun1HSBancpee",
	"Bfa3V7ecHspT3i+4jEHjKDyNfTtgLz4He7E1T05jGRQa0Let5M+U88VmeLZWumwge0aolNHdF55gjHLk",
	"+C4H497ZBTVwF41aiCx2vsNA+5ZVJ71IRSEFTwORiniPc7OGcaT4Hn+wrIU1/2zLc5Tx9355fb/0Rxua",
	"hWrZKPmFPRKdj/TI7WD8ru+vPK++zN32NAqlfJlDd0sugwufiLHKu+f3wRSymZwLcc40bK+No/zNnFkt",
	"u/8DAAD///rfmQN7DQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
